"use client";

// import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ParallaxProvider } from "react-scroll-parallax";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "SD Enterprises",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ParallaxProvider>
        <body className={inter.className}>{children}</body>
      </ParallaxProvider>
    </html>
  );
}
